/**
 * AQUASENSE - Mock Data Layer for Demo Mode & Offline Evaluation
 * Provides 25+ realistic clinical cases, 5 public health alerts,
 * and pre-aggregated analytics for hackathon demonstrations.
 */

export const INITIAL_MOCK_STATS = {
  totalCases: 34,
  casesToday: 4,
  highRiskAreas: 2,
  activeAlerts: 3,
};

export const INITIAL_MOCK_CASES = [
  // --- CLUSTER 1: Riverbank Slum Colony (CRITICAL Hotspot) ---
  {
    _id: "c-001",
    caseId: "CASE-HOT-001",
    age: 34,
    gender: "FEMALE",
    symptoms: ["Watery Diarrhea", "Severe Dehydration", "Vomiting"],
    suspectedDisease: "Cholera",
    symptomDate: "2026-10-08T04:30:00Z",
    reportedDate: "2026-10-08T06:00:00Z",
    severity: "CRITICAL",
    district: "Central Metro",
    locality: "Riverbank Slum Colony",
    latitude: 12.9612,
    longitude: 77.5854,
    waterSource: "Flooded Riverbank Tap",
    waterQualityConcern: true,
    flooding: true,
    similarCasesNearby: 14,
    riskScore: 94,
    riskLevel: "CRITICAL",
    status: "CONFIRMED",
    createdBy: "Nurse Priya"
  },
  {
    _id: "c-002",
    caseId: "CASE-HOT-002",
    age: 8,
    gender: "MALE",
    symptoms: ["Watery Diarrhea", "Vomiting", "Lethargy"],
    suspectedDisease: "Cholera",
    symptomDate: "2026-10-08T03:00:00Z",
    reportedDate: "2026-10-08T05:30:00Z",
    severity: "CRITICAL",
    district: "Central Metro",
    locality: "Riverbank Slum Colony",
    latitude: 12.9615,
    longitude: 77.5858,
    waterSource: "Flooded Riverbank Tap",
    waterQualityConcern: true,
    flooding: true,
    similarCasesNearby: 14,
    riskScore: 92,
    riskLevel: "CRITICAL",
    status: "INVESTIGATING",
    createdBy: "Nurse Priya"
  },
  {
    _id: "c-003",
    caseId: "CASE-HOT-003",
    age: 45,
    gender: "MALE",
    symptoms: ["Watery Diarrhea", "Abdominal Cramps", "Vomiting"],
    suspectedDisease: "Cholera",
    symptomDate: "2026-10-07T18:00:00Z",
    reportedDate: "2026-10-08T02:00:00Z",
    severity: "CRITICAL",
    district: "Central Metro",
    locality: "Riverbank Slum Colony",
    latitude: 12.9609,
    longitude: 77.5851,
    waterSource: "Contaminated Open Well",
    waterQualityConcern: true,
    flooding: true,
    similarCasesNearby: 13,
    riskScore: 89,
    riskLevel: "CRITICAL",
    status: "CONFIRMED",
    createdBy: "Worker Rajesh"
  },
  {
    _id: "c-004",
    caseId: "CASE-HOT-004",
    age: 22,
    gender: "FEMALE",
    symptoms: ["Watery Diarrhea", "Vomiting"],
    suspectedDisease: "Cholera",
    symptomDate: "2026-10-07T12:00:00Z",
    reportedDate: "2026-10-07T16:00:00Z",
    severity: "HIGH",
    district: "Central Metro",
    locality: "Riverbank Slum Colony",
    latitude: 12.9618,
    longitude: 77.5862,
    waterSource: "Contaminated Open Well",
    waterQualityConcern: true,
    flooding: true,
    similarCasesNearby: 12,
    riskScore: 86,
    riskLevel: "CRITICAL",
    status: "INVESTIGATING",
    createdBy: "Worker Rajesh"
  },
  {
    _id: "c-005",
    caseId: "CASE-HOT-005",
    age: 62,
    gender: "MALE",
    symptoms: ["Severe Dehydration", "Watery Diarrhea", "Muscle Cramps"],
    suspectedDisease: "Cholera",
    symptomDate: "2026-10-07T08:00:00Z",
    reportedDate: "2026-10-07T14:00:00Z",
    severity: "CRITICAL",
    district: "Central Metro",
    locality: "Riverbank Slum Colony",
    latitude: 12.9605,
    longitude: 77.5849,
    waterSource: "Flooded Riverbank Tap",
    waterQualityConcern: true,
    flooding: true,
    similarCasesNearby: 11,
    riskScore: 91,
    riskLevel: "CRITICAL",
    status: "REPORTED",
    createdBy: "Nurse Priya"
  },
  {
    _id: "c-006",
    caseId: "CASE-HOT-006",
    age: 29,
    gender: "FEMALE",
    symptoms: ["Watery Diarrhea", "Nausea", "Abdominal Pain"],
    suspectedDisease: "Acute Gastroenteritis",
    symptomDate: "2026-10-06T15:00:00Z",
    reportedDate: "2026-10-06T19:00:00Z",
    severity: "HIGH",
    district: "Central Metro",
    locality: "Riverbank Slum Colony",
    latitude: 12.9622,
    longitude: 77.5855,
    waterSource: "Flooded Riverbank Tap",
    waterQualityConcern: true,
    flooding: true,
    similarCasesNearby: 10,
    riskScore: 84,
    riskLevel: "CRITICAL",
    status: "CONFIRMED",
    createdBy: "Nurse Priya"
  },
  {
    _id: "c-007",
    caseId: "CASE-HOT-007",
    age: 14,
    gender: "MALE",
    symptoms: ["Watery Diarrhea", "Vomiting", "Dehydration"],
    suspectedDisease: "Cholera",
    symptomDate: "2026-10-06T10:00:00Z",
    reportedDate: "2026-10-06T14:00:00Z",
    severity: "HIGH",
    district: "Central Metro",
    locality: "Riverbank Slum Colony",
    latitude: 12.9611,
    longitude: 77.5859,
    waterSource: "Contaminated Open Well",
    waterQualityConcern: true,
    flooding: true,
    similarCasesNearby: 9,
    riskScore: 82,
    riskLevel: "CRITICAL",
    status: "INVESTIGATING",
    createdBy: "Worker Rajesh"
  },
  {
    _id: "c-008",
    caseId: "CASE-HOT-008",
    age: 40,
    gender: "FEMALE",
    symptoms: ["Watery Diarrhea", "Abdominal Cramps"],
    suspectedDisease: "Acute Gastroenteritis",
    symptomDate: "2026-10-05T12:00:00Z",
    reportedDate: "2026-10-05T16:00:00Z",
    severity: "HIGH",
    district: "Central Metro",
    locality: "Riverbank Slum Colony",
    latitude: 12.9614,
    longitude: 77.5847,
    waterSource: "Flooded Riverbank Tap",
    waterQualityConcern: true,
    flooding: true,
    similarCasesNearby: 8,
    riskScore: 80,
    riskLevel: "CRITICAL",
    status: "CONFIRMED",
    createdBy: "Nurse Priya"
  },
  {
    _id: "c-009",
    caseId: "CASE-HOT-009",
    age: 51,
    gender: "MALE",
    symptoms: ["Vomiting", "Watery Diarrhea", "Weakness"],
    suspectedDisease: "Cholera",
    symptomDate: "2026-10-05T08:00:00Z",
    reportedDate: "2026-10-05T12:00:00Z",
    severity: "HIGH",
    district: "Central Metro",
    locality: "Riverbank Slum Colony",
    latitude: 12.9607,
    longitude: 77.5864,
    waterSource: "Flooded Riverbank Tap",
    waterQualityConcern: true,
    flooding: true,
    similarCasesNearby: 7,
    riskScore: 78,
    riskLevel: "CRITICAL",
    status: "REPORTED",
    createdBy: "Worker Rajesh"
  },
  {
    _id: "c-010",
    caseId: "CASE-HOT-010",
    age: 19,
    gender: "FEMALE",
    symptoms: ["Watery Diarrhea", "Nausea"],
    suspectedDisease: "Acute Gastroenteritis",
    symptomDate: "2026-10-04T11:00:00Z",
    reportedDate: "2026-10-04T15:00:00Z",
    severity: "MODERATE",
    district: "Central Metro",
    locality: "Riverbank Slum Colony",
    latitude: 12.9620,
    longitude: 77.5852,
    waterSource: "Contaminated Open Well",
    waterQualityConcern: true,
    flooding: false,
    similarCasesNearby: 6,
    riskScore: 68,
    riskLevel: "HIGH",
    status: "RESOLVED",
    createdBy: "Nurse Priya"
  },

  // --- CLUSTER 2: Old Market Basti (HIGH Risk Area) ---
  {
    _id: "c-011",
    caseId: "CASE-INC-001",
    age: 38,
    gender: "MALE",
    symptoms: ["High Fever", "Watery Diarrhea", "Abdominal Pain"],
    suspectedDisease: "Typhoid",
    symptomDate: "2026-10-08T05:00:00Z",
    reportedDate: "2026-10-08T07:00:00Z",
    severity: "HIGH",
    district: "Central Metro",
    locality: "Old Market Basti",
    latitude: 12.9782,
    longitude: 77.5924,
    waterSource: "Broken Municipal Pipeline",
    waterQualityConcern: true,
    flooding: false,
    similarCasesNearby: 8,
    riskScore: 74,
    riskLevel: "HIGH",
    status: "INVESTIGATING",
    createdBy: "Worker Sunita"
  },
  {
    _id: "c-012",
    caseId: "CASE-INC-002",
    age: 21,
    gender: "FEMALE",
    symptoms: ["Watery Diarrhea", "Abdominal Cramps", "Vomiting"],
    suspectedDisease: "Acute Gastroenteritis",
    symptomDate: "2026-10-07T14:00:00Z",
    reportedDate: "2026-10-07T18:00:00Z",
    severity: "HIGH",
    district: "Central Metro",
    locality: "Old Market Basti",
    latitude: 12.9786,
    longitude: 77.5929,
    waterSource: "Broken Municipal Pipeline",
    waterQualityConcern: true,
    flooding: false,
    similarCasesNearby: 8,
    riskScore: 71,
    riskLevel: "HIGH",
    status: "CONFIRMED",
    createdBy: "Worker Sunita"
  },
  {
    _id: "c-013",
    caseId: "CASE-INC-003",
    age: 47,
    gender: "MALE",
    symptoms: ["Fever", "Bloody Stool", "Abdominal Cramps"],
    suspectedDisease: "Dysentery",
    symptomDate: "2026-10-07T09:00:00Z",
    reportedDate: "2026-10-07T13:00:00Z",
    severity: "HIGH",
    district: "Central Metro",
    locality: "Old Market Basti",
    latitude: 12.9778,
    longitude: 77.5919,
    waterSource: "Broken Municipal Pipeline",
    waterQualityConcern: true,
    flooding: false,
    similarCasesNearby: 7,
    riskScore: 69,
    riskLevel: "HIGH",
    status: "REPORTED",
    createdBy: "Worker Sunita"
  },
  {
    _id: "c-014",
    caseId: "CASE-INC-004",
    age: 16,
    gender: "FEMALE",
    symptoms: ["Watery Diarrhea", "Nausea", "Fever"],
    suspectedDisease: "Acute Gastroenteritis",
    symptomDate: "2026-10-06T11:00:00Z",
    reportedDate: "2026-10-06T15:00:00Z",
    severity: "MODERATE",
    district: "Central Metro",
    locality: "Old Market Basti",
    latitude: 12.9789,
    longitude: 77.5925,
    waterSource: "Broken Municipal Pipeline",
    waterQualityConcern: true,
    flooding: false,
    similarCasesNearby: 6,
    riskScore: 62,
    riskLevel: "HIGH",
    status: "INVESTIGATING",
    createdBy: "Worker Sunita"
  },
  {
    _id: "c-015",
    caseId: "CASE-INC-005",
    age: 55,
    gender: "FEMALE",
    symptoms: ["High Fever", "Chills", "Abdominal Pain"],
    suspectedDisease: "Typhoid",
    symptomDate: "2026-10-05T08:00:00Z",
    reportedDate: "2026-10-05T12:00:00Z",
    severity: "MODERATE",
    district: "Central Metro",
    locality: "Old Market Basti",
    latitude: 12.9780,
    longitude: 77.5932,
    waterSource: "Broken Municipal Pipeline",
    waterQualityConcern: true,
    flooding: false,
    similarCasesNearby: 5,
    riskScore: 58,
    riskLevel: "HIGH",
    status: "CONFIRMED",
    createdBy: "Worker Sunita"
  },
  {
    _id: "c-016",
    caseId: "CASE-INC-006",
    age: 11,
    gender: "MALE",
    symptoms: ["Watery Diarrhea", "Vomiting"],
    suspectedDisease: "Acute Gastroenteritis",
    symptomDate: "2026-10-04T14:00:00Z",
    reportedDate: "2026-10-04T17:00:00Z",
    severity: "MODERATE",
    district: "Central Metro",
    locality: "Old Market Basti",
    latitude: 12.9784,
    longitude: 77.5918,
    waterSource: "Broken Municipal Pipeline",
    waterQualityConcern: false,
    flooding: false,
    similarCasesNearby: 4,
    riskScore: 54,
    riskLevel: "HIGH",
    status: "RESOLVED",
    createdBy: "Worker Sunita"
  },

  // --- CLUSTER 3: Sector 4 Industrial Colony (MODERATE Risk) ---
  {
    _id: "c-017",
    caseId: "CASE-MOD-001",
    age: 28,
    gender: "MALE",
    symptoms: ["Abdominal Cramps", "Watery Diarrhea"],
    suspectedDisease: "Dysentery",
    symptomDate: "2026-10-07T07:00:00Z",
    reportedDate: "2026-10-07T11:00:00Z",
    severity: "MODERATE",
    district: "South Industrial",
    locality: "Sector 4 Industrial Colony",
    latitude: 12.9354,
    longitude: 77.6105,
    waterSource: "Industrial Worker Tanker",
    waterQualityConcern: true,
    flooding: false,
    similarCasesNearby: 5,
    riskScore: 48,
    riskLevel: "MODERATE",
    status: "INVESTIGATING",
    createdBy: "Health Officer Kiran"
  },
  {
    _id: "c-018",
    caseId: "CASE-MOD-002",
    age: 32,
    gender: "FEMALE",
    symptoms: ["Nausea", "Mild Diarrhea", "Fever"],
    suspectedDisease: "Acute Gastroenteritis",
    symptomDate: "2026-10-06T13:00:00Z",
    reportedDate: "2026-10-06T17:00:00Z",
    severity: "MODERATE",
    district: "South Industrial",
    locality: "Sector 4 Industrial Colony",
    latitude: 12.9351,
    longitude: 77.6101,
    waterSource: "Industrial Worker Tanker",
    waterQualityConcern: true,
    flooding: false,
    similarCasesNearby: 4,
    riskScore: 45,
    riskLevel: "MODERATE",
    status: "CONFIRMED",
    createdBy: "Health Officer Kiran"
  },
  {
    _id: "c-019",
    caseId: "CASE-MOD-003",
    age: 41,
    gender: "MALE",
    symptoms: ["Abdominal Pain", "Vomiting"],
    suspectedDisease: "Acute Gastroenteritis",
    symptomDate: "2026-10-05T09:00:00Z",
    reportedDate: "2026-10-05T13:00:00Z",
    severity: "MODERATE",
    district: "South Industrial",
    locality: "Sector 4 Industrial Colony",
    latitude: 12.9358,
    longitude: 77.6109,
    waterSource: "Industrial Worker Tanker",
    waterQualityConcern: false,
    flooding: false,
    similarCasesNearby: 3,
    riskScore: 42,
    riskLevel: "MODERATE",
    status: "REPORTED",
    createdBy: "Health Officer Kiran"
  },

  // --- CLUSTER 4: Normal / Baseline Areas (LOW Risk) ---
  {
    _id: "c-020",
    caseId: "CASE-NORM-001",
    age: 27,
    gender: "FEMALE",
    symptoms: ["Mild Nausea", "Headache"],
    suspectedDisease: "Acute Gastroenteritis",
    symptomDate: "2026-10-06T08:00:00Z",
    reportedDate: "2026-10-06T12:00:00Z",
    severity: "LOW",
    district: "East Suburbs",
    locality: "Greenfield Heights",
    latitude: 12.9912,
    longitude: 77.6515,
    waterSource: "Treated Piped Municipal",
    waterQualityConcern: false,
    flooding: false,
    similarCasesNearby: 1,
    riskScore: 18,
    riskLevel: "LOW",
    status: "RESOLVED",
    createdBy: "Dr. Vikram"
  },
  {
    _id: "c-021",
    caseId: "CASE-NORM-002",
    age: 36,
    gender: "MALE",
    symptoms: ["Mild Diarrhea"],
    suspectedDisease: "Acute Gastroenteritis",
    symptomDate: "2026-10-04T10:00:00Z",
    reportedDate: "2026-10-04T14:00:00Z",
    severity: "LOW",
    district: "East Suburbs",
    locality: "Greenfield Heights",
    latitude: 12.9908,
    longitude: 77.6521,
    waterSource: "Treated Piped Municipal",
    waterQualityConcern: false,
    flooding: false,
    similarCasesNearby: 0,
    riskScore: 15,
    riskLevel: "LOW",
    status: "RESOLVED",
    createdBy: "Dr. Vikram"
  },
  {
    _id: "c-022",
    caseId: "CASE-NORM-003",
    age: 48,
    gender: "FEMALE",
    symptoms: ["Abdominal Discomfort", "Fatigue"],
    suspectedDisease: "Acute Gastroenteritis",
    symptomDate: "2026-10-05T07:00:00Z",
    reportedDate: "2026-10-05T11:00:00Z",
    severity: "LOW",
    district: "South Cantonment",
    locality: "Silver Oaks Cantonment",
    latitude: 12.9152,
    longitude: 77.6418,
    waterSource: "Reverse Osmosis Filtered Supply",
    waterQualityConcern: false,
    flooding: false,
    similarCasesNearby: 1,
    riskScore: 16,
    riskLevel: "LOW",
    status: "RESOLVED",
    createdBy: "Dr. Vikram"
  },
  {
    _id: "c-023",
    caseId: "CASE-NORM-004",
    age: 52,
    gender: "MALE",
    symptoms: ["Mild Diarrhea", "Fatigue"],
    suspectedDisease: "Acute Gastroenteritis",
    symptomDate: "2026-10-04T06:00:00Z",
    reportedDate: "2026-10-04T09:00:00Z",
    severity: "LOW",
    district: "West Hills",
    locality: "Central Hill Enclave",
    latitude: 12.9715,
    longitude: 77.5612,
    waterSource: "Treated Piped Municipal",
    waterQualityConcern: false,
    flooding: false,
    similarCasesNearby: 0,
    riskScore: 20,
    riskLevel: "LOW",
    status: "RESOLVED",
    createdBy: "Dr. Vikram"
  },
  {
    _id: "c-024",
    caseId: "CASE-NORM-005",
    age: 39,
    gender: "FEMALE",
    symptoms: ["Fever", "Nausea"],
    suspectedDisease: "Typhoid",
    symptomDate: "2026-10-03T11:00:00Z",
    reportedDate: "2026-10-03T15:00:00Z",
    severity: "MODERATE",
    district: "East Suburbs",
    locality: "Lakeview Gardens",
    latitude: 12.9845,
    longitude: 77.6250,
    waterSource: "Treated Piped Municipal",
    waterQualityConcern: false,
    flooding: false,
    similarCasesNearby: 1,
    riskScore: 28,
    riskLevel: "LOW",
    status: "INVESTIGATING",
    createdBy: "Dr. Vikram"
  },
  {
    _id: "c-025",
    caseId: "CASE-EXTRA-001",
    age: 30,
    gender: "MALE",
    symptoms: ["Watery Diarrhea", "Vomiting", "Abdominal Cramps"],
    suspectedDisease: "Cholera",
    symptomDate: "2026-10-08T07:00:00Z",
    reportedDate: "2026-10-08T08:30:00Z",
    severity: "CRITICAL",
    district: "Central Metro",
    locality: "Riverbank Slum Colony",
    latitude: 12.9616,
    longitude: 77.5857,
    waterSource: "Flooded Riverbank Tap",
    waterQualityConcern: true,
    flooding: true,
    similarCasesNearby: 15,
    riskScore: 95,
    riskLevel: "CRITICAL",
    status: "REPORTED",
    createdBy: "Nurse Priya"
  }
];

export const INITIAL_MOCK_ALERTS = [
  {
    _id: "a-001",
    alertId: "ALT-2026-HOT-01",
    location: "Riverbank Slum Colony",
    riskLevel: "CRITICAL",
    caseCount: 16,
    createdAt: "2026-10-08T06:15:00Z",
    reason: "Epidemic surge detected: Rapid cluster of acute watery diarrhea and suspected Cholera following riverbank inundation.",
    recommendedAction: "URGENT: Deploy rapid epidemic response team to Riverbank Slum Colony. Initiate immediate oral rehydration posts (ORT), distribute chlorine tablets, and shut down unboiled surface taps.",
    status: "ACTIVE"
  },
  {
    _id: "a-002",
    alertId: "ALT-2026-INC-02",
    location: "Old Market Basti",
    riskLevel: "HIGH",
    caseCount: 9,
    createdAt: "2026-10-07T18:45:00Z",
    reason: "Accelerating cluster of acute gastrointestinal infections and Typhoid linked to cracked municipal distribution line.",
    recommendedAction: "HIGH PRIORITY: Issue boiled-water advisory for Old Market Basti. Dispatch municipal engineering crew to isolate cracked main pipeline section and conduct chlorination.",
    status: "ACTIVE"
  },
  {
    _id: "a-003",
    alertId: "ALT-2026-MOD-03",
    location: "Sector 4 Industrial Colony",
    riskLevel: "MODERATE",
    caseCount: 5,
    createdAt: "2026-10-06T14:20:00Z",
    reason: "Elevated case count identified among factory worker dormitories utilizing unverified private water tanker service.",
    recommendedAction: "Inspect commercial water delivery tankers servicing Sector 4. Conduct microbiological testing of storage cisterns.",
    status: "ACKNOWLEDGED"
  },
  {
    _id: "a-004",
    alertId: "ALT-2026-RES-04",
    location: "Central Hill Enclave",
    riskLevel: "LOW",
    caseCount: 2,
    createdAt: "2026-10-04T10:00:00Z",
    reason: "Sporadic mild gastroenteritis cases. Water testing negative for fecal coliform.",
    recommendedAction: "Maintain standard periodic water quality monitoring.",
    status: "RESOLVED"
  },
  {
    _id: "a-005",
    alertId: "ALT-2026-RES-05",
    location: "Greenfield Heights",
    riskLevel: "LOW",
    caseCount: 2,
    createdAt: "2026-10-03T16:00:00Z",
    reason: "Isolated cases with no transmission clusters detected. Normal municipal chlorine residuals confirmed.",
    recommendedAction: "Routine surveillance vigilance.",
    status: "RESOLVED"
  }
];

export const MOCK_TRENDS = [
  { date: "Sep 29", count: 2 },
  { date: "Sep 30", count: 1 },
  { date: "Oct 01", count: 3 },
  { date: "Oct 02", count: 2 },
  { date: "Oct 03", count: 4 },
  { date: "Oct 04", count: 5 },
  { date: "Oct 05", count: 7 },
  { date: "Oct 06", count: 9 },
  { date: "Oct 07", count: 13 },
  { date: "Oct 08", count: 18 },
];

export const MOCK_SYMPTOMS = [
  { symptom: "Watery Diarrhea", count: 26, percentage: 33.3 },
  { symptom: "Vomiting", count: 18, percentage: 23.1 },
  { symptom: "Abdominal Cramps", count: 15, percentage: 19.2 },
  { symptom: "Severe Dehydration", count: 9, percentage: 11.5 },
  { symptom: "High Fever", count: 8, percentage: 10.3 },
  { symptom: "Nausea", count: 6, percentage: 7.7 },
  { symptom: "Bloody Stool", count: 2, percentage: 2.6 },
];

export const MOCK_LOCATIONS = [
  {
    locality: "Riverbank Slum Colony",
    district: "Central Metro",
    count: 16,
    averageRiskScore: 88,
    riskLevel: "CRITICAL",
    latitude: 12.9612,
    longitude: 77.5854,
    waterQualityConcerns: 16,
    floodingReports: 14
  },
  {
    locality: "Old Market Basti",
    district: "Central Metro",
    count: 9,
    averageRiskScore: 68,
    riskLevel: "HIGH",
    latitude: 12.9782,
    longitude: 77.5924,
    waterQualityConcerns: 8,
    floodingReports: 0
  },
  {
    locality: "Sector 4 Industrial Colony",
    district: "South Industrial",
    count: 5,
    averageRiskScore: 45,
    riskLevel: "MODERATE",
    latitude: 12.9354,
    longitude: 77.6105,
    waterQualityConcerns: 4,
    floodingReports: 0
  },
  {
    locality: "Greenfield Heights",
    district: "East Suburbs",
    count: 2,
    averageRiskScore: 17,
    riskLevel: "LOW",
    latitude: 12.9912,
    longitude: 77.6515,
    waterQualityConcerns: 0,
    floodingReports: 0
  },
  {
    locality: "Silver Oaks Cantonment",
    district: "South Cantonment",
    count: 1,
    averageRiskScore: 16,
    riskLevel: "LOW",
    latitude: 12.9152,
    longitude: 77.6418,
    waterQualityConcerns: 0,
    floodingReports: 0
  },
  {
    locality: "Central Hill Enclave",
    district: "West Hills",
    count: 1,
    averageRiskScore: 20,
    riskLevel: "LOW",
    latitude: 12.9715,
    longitude: 77.5612,
    waterQualityConcerns: 0,
    floodingReports: 0
  }
];

export const MOCK_RISK_DISTRIBUTION = {
  low: 12,
  moderate: 7,
  high: 6,
  critical: 9,
};

export const MOCK_ANOMALY_INFO = {
  is_anomaly: true,
  statistical_anomaly: true,
  isolation_forest_anomaly: true,
  current_count: 18,
  baseline_mean: 4.2,
  z_score: 8.6,
  percentage_increase: 328.6,
  reason: "Spike of 18 cases/day significantly exceeds baseline mean of 4.2 cases/day; +328.6% surge flagged by Isolation Forest multivariate outlier model"
};
